backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "materiais"
    label: "Materiais"
    files:
      - label: "Lista de Materiais"
        name: "materiais_lista"
        file: "materiais.json"
        fields:
          - label: "Lista de Materiais"
            name: "materiais"
            widget: "list"
            fields:
              - { label: "Nome do Material", name: "nome", widget: "string" }
              - { label: "Imagem", name: "imagem", widget: "image" }
              - { label: "Texto Alternativo da Imagem", name: "alt", widget: "string" }

  - name: "projetos"
    label: "Projetos"
    files:
      - label: "Lista de Projetos"
        name: "projetos_lista"
        file: "projetos.json"
        fields:
          - label: "Lista de Projetos"
            name: "projetos"
            widget: "list"
            fields:
              - { label: "Título do Projeto", name: "titulo", widget: "string" }
              - { label: "Descrição (Material Usado)", name: "descricao", widget: "string" }
              - { label: "Imagem do Projeto", name: "imagem", widget: "image" }
              - { label: "Texto Alternativo da Imagem", name: "alt", widget: "string" }